export const REGISTER_PROCESS = "REGISTER_PROCESS";
export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGOUT_PROCESS = "LOGOUT_PROCESS";
export const AUTH_PROCESS = "AUTH_PROCESS";
export const VERIFY_PROCESS = "VERIFY_PROCESS";
