export const REGISTER_PROCESS = "REGISTER_PROCESS";
export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGOUT_PROCESS = "LOGOUT_PROCESS";
export const GET_PROFILE = "GET_PROFILE";
export const POST_PROFILE = "POST_PROFILE"